version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2017
build_script:
- cmd: >-
    IF /I "%APPVEYOR_REPO_TAG%" EQU "TRUE" SET Configuration=Release

    MSBuild.exe /BinaryLogger /Logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    MSBuild.exe Samples\VerifySamples\VerifySamples.proj /BinaryLogger:Samples\VerifySamples\VerifySamples.binlog /Logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
on_failure:
- ps: Get-ChildItem .\*.binlog -Recursive | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

